import { createFileRoute } from '@tanstack/react-router'
import HomePage from '../components/pages/home/HomePage'
import { convexQuery } from '@convex-dev/react-query'
import { api } from '../../convex/_generated/api'
import { convexHttpClient } from '../integrations/convex/provider'

export const Route = createFileRoute('/')({
  component: HomePage,
  loader: async ({ context: { queryClient } }) => {
    if (typeof document === 'undefined') {
      // Fetch directly via HTTP on the server to avoid WebSocket issues
      const [berandaData, perangkatData, beritaData] = await Promise.all([
        convexHttpClient.query(api.beranda.getBerandaConfig, {}),
        convexHttpClient.query(api.perangkat.getPerangkatList, {
          status: 'Aktif',
        }),
        convexHttpClient.query(api.berita.getBerita, {}),
      ])

      // Inject into QueryClient cache manually using the keys generated by convexQuery
      // We fall back to null if undefined to ensure TanStack Query accepts it
      queryClient.setQueryData(
        convexQuery(api.beranda.getBerandaConfig, {}).queryKey,
        berandaData ?? null,
      )
      queryClient.setQueryData(
        convexQuery(api.perangkat.getPerangkatList, { status: 'Aktif' })
          .queryKey,
        perangkatData ?? null,
      )
      queryClient.setQueryData(
        convexQuery(api.berita.getBerita, {}).queryKey,
        beritaData ?? [],
      )
    } else {
      // On the client, use the normal ensureQueryData which will use the WebSocket
      await Promise.all([
        queryClient.ensureQueryData(
          convexQuery(api.beranda.getBerandaConfig, {}),
        ),
        queryClient.ensureQueryData(
          convexQuery(api.perangkat.getPerangkatList, { status: 'Aktif' }),
        ),
        queryClient.ensureQueryData(convexQuery(api.berita.getBerita, {})),
      ])
    }
  },
})
