import { createFileRoute } from '@tanstack/react-router'
import { ConvexHttpClient } from 'convex/browser'
import HomePage from '../components/pages/home/HomePage'
import { convexQuery } from '@convex-dev/react-query'
import { api } from '../../convex/_generated/api'
import {
  getServerConvexUrl,
  hasValidServerConvexUrl,
  warnInvalidConvexUrlOnce,
} from '../lib/convex-env'

export const Route = createFileRoute('/')({
  component: HomePage,
  loader: async ({ context: { queryClient } }) => {
    try {
      if (typeof document === 'undefined') {
        if (!(await hasValidServerConvexUrl())) {
          warnInvalidConvexUrlOnce('SSR homepage loader dilewati')
          return
        }

        const serverConvexUrl = await getServerConvexUrl()
        const serverConvexClient = new ConvexHttpClient(serverConvexUrl!)

        // Fetch directly via HTTP on the server to avoid WebSocket issues
        const [berandaData, perangkatData, beritaData] = await Promise.all([
          serverConvexClient.query(api.beranda.getBerandaConfig, {}),
          serverConvexClient.query(api.perangkat.getPerangkatList, {
            status: 'Aktif',
          }),
          serverConvexClient.query(api.berita.getBerita, {}),
        ])

        // Inject into QueryClient cache manually using the keys generated by convexQuery
        // We fall back to null if undefined to ensure TanStack Query accepts it
        queryClient.setQueryData(
          convexQuery(api.beranda.getBerandaConfig, {}).queryKey,
          berandaData ?? null,
        )
        queryClient.setQueryData(
          convexQuery(api.perangkat.getPerangkatList, { status: 'Aktif' })
            .queryKey,
          perangkatData ?? null,
        )
        queryClient.setQueryData(
          convexQuery(api.berita.getBerita, {}).queryKey,
          beritaData ?? [],
        )
      } else {
        // On the client, use the normal ensureQueryData which will use the WebSocket
        await Promise.all([
          queryClient.ensureQueryData(
            convexQuery(api.beranda.getBerandaConfig, {}),
          ),
          queryClient.ensureQueryData(
            convexQuery(api.perangkat.getPerangkatList, { status: 'Aktif' }),
          ),
          queryClient.ensureQueryData(convexQuery(api.berita.getBerita, {})),
        ])
      }
    } catch (error) {
      console.error('Gagal memuat data homepage saat SSR:', error)
    }
  },
})
