export const bpdAnggota = [
  { nama: 'CH.A.ALI WAHYUDI, S.E', jabatan: 'Ketua (merangkap anggota)' },
  { nama: 'KHOIRUL AMININ, S.E', jabatan: 'Wakil Ketua (merangkap anggota)' },
  {
    nama: "BADI'UL HASNIAH, A.Md.Keb",
    jabatan: 'Sekretaris (merangkap anggota)',
  },
  { nama: 'HENDRI WAHANANTO', jabatan: 'Ketua Komisi I' },
  { nama: 'LASMIANTO', jabatan: 'Anggota Komisi I' },
  { nama: 'MOH.YASIN YUSUF, S.E', jabatan: 'Anggota Komisi I' },
  { nama: 'GUNAWAN', jabatan: 'Ketua Komisi II' },
  { nama: 'CHOIRUL ANWAR', jabatan: 'Anggota Komisi II' },
  { nama: 'HERIMAWAN', jabatan: 'Anggota Komisi II' },
]

export const lpmdAnggota = [
  { nama: 'MUHAMMAD MASRUHIN', jabatan: 'Ketua' },
  { nama: 'MUJIANTO', jabatan: 'Sekretaris' },
  { nama: 'GIYONO', jabatan: 'Bendahara' },
  { nama: 'MAT ROKIM', jabatan: 'Ka. Seksi Pembangunan & Ekonomi' },
  { nama: 'SUKARJI', jabatan: 'Ka. Seksi Keamanan & Lingkungan' },
  { nama: 'SUGIATNO', jabatan: 'Ka. Seksi Keagamaan' },
  { nama: 'SUNARWAN', jabatan: 'Ka. Seksi Pendidikan & Kebudayaan' },
  { nama: 'MAWAN', jabatan: 'Ka. Seksi Pemuda & Olahraga' },
  { nama: 'MUHIMMATUL ALIYAH', jabatan: 'Ka. Seksi Pemberdayaan Perempuan' },
]

export const pkkAnggota = [
  { nama: 'MUHIMMATUL ALIYAH', jabatan: 'Ketua Badan Penyantun' },
  { nama: 'DIYAH WIDIARINI', jabatan: 'Sekretaris Badan Penyantun' },
  { nama: 'WIWIK SRI KARYATI', jabatan: 'Bendahara Badan Penyantun' },
  { nama: 'NUNIK / SRIANI', jabatan: 'Ketua Pokja I' },
  { nama: 'SUGIARTI', jabatan: 'Wakil Ketua Pokja I' },
  { nama: 'MUSAROPAH', jabatan: 'Sekretaris Pokja I' },
  { nama: 'ISNAWATI', jabatan: 'Anggota Pokja I' },
  { nama: 'SUSIANI', jabatan: 'Ketua Pokja II' },
  { nama: 'NENI RAHAYU', jabatan: 'Wakil Ketua Pokja II' },
  { nama: 'INDRININGSIH', jabatan: 'Sekretaris Pokja II' },
  { nama: 'ANIS RIKA FEBRIANTI', jabatan: 'Anggota Pokja II' },
  { nama: 'LIA KURNIASIH', jabatan: 'Ketua Pokja III' },
  { nama: 'DWI LESTARI', jabatan: 'Wakil Ketua Pokja III' },
  { nama: "PATO'AH", jabatan: 'Sekretaris Pokja III' },
  { nama: 'TUTIK IIS SUDIARTI', jabatan: 'Anggota Pokja III' },
  { nama: 'MARSINI', jabatan: 'Ketua Pokja IV' },
  { nama: 'SULIANI', jabatan: 'Wakil Ketua Pokja IV' },
  { nama: 'WINARSIH ARIMI', jabatan: 'Sekretaris Pokja IV' },
  { nama: 'EVI NUR FITRIANAN', jabatan: 'Anggota Pokja IV' },
  { nama: 'ARITA DWI NINGTIYAS', jabatan: 'Anggota Pokja IV' },
]

export const ktAnggota = [
  { nama: 'UNTUNG LESTARI', jabatan: 'Ketua Umum' },
  { nama: 'DODIK PRASETIAWAN', jabatan: 'Wakil Ketua Umum' },
  { nama: 'RUDI WIDAYANTO', jabatan: 'Sekretaris I' },
  { nama: 'EKIK PRIAMBODO', jabatan: 'Sekretaris II' },
  { nama: 'WIJIONO', jabatan: 'Bendahara I' },
  { nama: 'ELI KURNIAWATI', jabatan: 'Bendahara II' },
  { nama: 'ROBI WILI PURNOMO', jabatan: 'Ka. Seksi Olahraga' },
  { nama: 'SUGIYANTO', jabatan: 'Anggota Seksi Olahraga' },
  { nama: 'MOH. SIHABUDDIN', jabatan: 'Ka. Seksi Kesenian & Kebudayaan' },
  { nama: 'DEDEK NURYANTO', jabatan: 'Anggota Seksi Kesenian' },
  { nama: 'IBNU ABAS', jabatan: 'Ka. Seksi Keagamaan' },
  { nama: 'AGUS SANUSI', jabatan: 'Anggota Seksi Keagamaan' },
  { nama: 'ANTONI TIOSA', jabatan: 'Ka. Seksi Lingkungan Hidup' },
  { nama: 'NITA ERNAWATI', jabatan: 'Anggota Seksi Lingkungan' },
  { nama: 'PURNOMO', jabatan: 'Ka. Seksi Sosial Kemasyarakatan' },
  { nama: 'SURIPNO', jabatan: 'Anggota Seksi Sosial' },
  { nama: 'MOH. ARI HIDAYAT', jabatan: 'Anggota Seksi Sosial' },
  { nama: 'AGUS WIDODO', jabatan: 'Ka. Seksi Ketrampilan' },
  { nama: 'SUGENG WIYONO', jabatan: 'Anggota Seksi Ketrampilan' },
]

export const satlinmasAnggota = [
  { nama: 'ROIHAN AL MADZHAR', jabatan: 'Kepala Satuan Linmas' },
  { nama: 'SUKARJI', jabatan: 'Kasatgas (Wakil)' },
  { nama: 'TUKIMAN', jabatan: 'Danru Kesiapsiagaan & Kewaspadaan' },
  { nama: 'KATRIM', jabatan: 'Danru Pengamanan' },
  { nama: 'GIYAN', jabatan: 'Danru P3K' },
  { nama: 'EDI SULISTIONO', jabatan: 'Danru Penyelamatan & Evakuasi' },
  { nama: 'SUNARYASIN', jabatan: 'Danru Dapur Umum' },
  { nama: 'SUBIONO', jabatan: 'Anggota Regu Kesiapsiagaan' },
  { nama: 'SUMAJI', jabatan: 'Anggota Regu Kesiapsiagaan' },
  { nama: "SUPI'I", jabatan: 'Anggota Regu Kesiapsiagaan' },
  { nama: 'SUKIJAN', jabatan: 'Anggota Regu Kesiapsiagaan' },
  { nama: 'RIYANTO', jabatan: 'Anggota Regu Pengamanan' },
  { nama: 'BAMBANG RIADI', jabatan: 'Anggota Regu Pengamanan' },
  { nama: 'TRIONO', jabatan: 'Anggota Regu Pengamanan' },
  { nama: 'SATAM', jabatan: 'Anggota Regu Pengamanan' },
  { nama: 'PRIANGGORO', jabatan: 'Anggota Regu Pengamanan' },
  { nama: 'SUJITO', jabatan: 'Anggota Regu Pengamanan' },
  { nama: 'IMAM SYAFII', jabatan: 'Anggota Regu Pengamanan' },
  { nama: 'UKIK EKO PRAMONO', jabatan: 'Anggota Regu Pengamanan' },
  { nama: 'DUWAN', jabatan: 'Anggota Regu P3K' },
  { nama: 'SUDARSONO', jabatan: 'Anggota Regu P3K' },
  { nama: 'YANNI A', jabatan: 'Anggota Regu P3K' },
  { nama: 'SUDARMAJI', jabatan: 'Anggota Regu P3K' },
  { nama: 'ROHMAT', jabatan: 'Anggota Regu P3K' },
  { nama: 'JITO', jabatan: 'Anggota Regu Evakuasi' },
  { nama: 'SUYOTO', jabatan: 'Anggota Regu Evakuasi' },
  { nama: 'MARSIM', jabatan: 'Anggota Regu Evakuasi' },
  { nama: 'DARWADI', jabatan: 'Anggota Regu Evakuasi' },
  { nama: 'UMAR SAET', jabatan: 'Anggota Regu Dapur Umum' },
  { nama: 'SUGITO', jabatan: 'Anggota Regu Dapur Umum' },
  { nama: 'YAKUP', jabatan: 'Anggota Regu Dapur Umum' },
  { nama: 'SUWANDI', jabatan: 'Anggota Regu Dapur Umum' },
]

export const posyanduAnggota = [
  { nama: 'Bidan Desa / Tenaga Kesehatan', jabatan: 'Koordinator Posyandu' },
  { nama: 'Kader Posyandu Dusun Sambigede', jabatan: 'Kader Aktif' },
  { nama: 'Kader Posyandu Dusun Paldoyong', jabatan: 'Kader Aktif' },
]

export const perangkatList = [
  { no: 1, nama: 'Roihan Al Madzhar', jabatan: 'Kepala Desa' },
  { no: 2, nama: 'Agus Anang Styobudi, S.Kom', jabatan: 'Sekretaris Desa' },
  { no: 3, nama: 'Budi Kurniawan, S.Pd.SD', jabatan: 'Kasi Pemerintahan' },
  { no: 4, nama: 'Suhadi', jabatan: 'Kasi Kesejahteraan' },
  { no: 5, nama: 'Siti Nur Kolifah, S.Ak', jabatan: 'Kasi Pelayanan' },
  { no: 6, nama: 'Agus Wiyono', jabatan: 'Kaur Tata Usaha & Umum' },
  { no: 7, nama: 'Sunarmi', jabatan: 'Kaur Keuangan' },
  { no: 8, nama: 'Bibit Hasanuddin', jabatan: 'Kaur Perencanaan' },
  { no: 9, nama: 'Sundari', jabatan: 'Kamituwo Dusun Sambigede' },
  { no: 10, nama: 'Pitantoro', jabatan: 'Kamituwo Dusun Paldoyong' },
  { no: 11, nama: 'Imam Mahfud', jabatan: 'Karyawan Desa (Staf Kewilayahan)' },
  { no: 12, nama: 'Muhyiddin', jabatan: 'Karyawan Desa (Modin Islam)' },
  { no: 13, nama: 'Riadi', jabatan: 'Karyawan Desa (Kebersihan Kantor)' },
]
