/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as InfografisRouteImport } from './routes/infografis'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InfografisIndexRouteImport } from './routes/infografis/index'
import { Route as BeritaIndexRouteImport } from './routes/berita/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as InfografisStuntingRouteImport } from './routes/infografis/stunting'
import { Route as InfografisPendudukRouteImport } from './routes/infografis/penduduk'
import { Route as InfografisBansosRouteImport } from './routes/infografis/bansos'
import { Route as InfografisApbdesRouteImport } from './routes/infografis/apbdes'
import { Route as BeritaIdRouteImport } from './routes/berita/$id'
import { Route as AdminStuntingRouteImport } from './routes/admin/stunting'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPendudukRouteImport } from './routes/admin/penduduk'
import { Route as AdminBeritaRouteImport } from './routes/admin/berita'
import { Route as AdminBansosRouteImport } from './routes/admin/bansos'
import { Route as AdminApbdesRouteImport } from './routes/admin/apbdes'

const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const InfografisRoute = InfografisRouteImport.update({
  id: '/infografis',
  path: '/infografis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfografisIndexRoute = InfografisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InfografisRoute,
} as any)
const BeritaIndexRoute = BeritaIndexRouteImport.update({
  id: '/berita/',
  path: '/berita/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const InfografisStuntingRoute = InfografisStuntingRouteImport.update({
  id: '/stunting',
  path: '/stunting',
  getParentRoute: () => InfografisRoute,
} as any)
const InfografisPendudukRoute = InfografisPendudukRouteImport.update({
  id: '/penduduk',
  path: '/penduduk',
  getParentRoute: () => InfografisRoute,
} as any)
const InfografisBansosRoute = InfografisBansosRouteImport.update({
  id: '/bansos',
  path: '/bansos',
  getParentRoute: () => InfografisRoute,
} as any)
const InfografisApbdesRoute = InfografisApbdesRouteImport.update({
  id: '/apbdes',
  path: '/apbdes',
  getParentRoute: () => InfografisRoute,
} as any)
const BeritaIdRoute = BeritaIdRouteImport.update({
  id: '/berita/$id',
  path: '/berita/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStuntingRoute = AdminStuntingRouteImport.update({
  id: '/stunting',
  path: '/stunting',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPendudukRoute = AdminPendudukRouteImport.update({
  id: '/penduduk',
  path: '/penduduk',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBeritaRoute = AdminBeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBansosRoute = AdminBansosRouteImport.update({
  id: '/bansos',
  path: '/bansos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApbdesRoute = AdminApbdesRouteImport.update({
  id: '/apbdes',
  path: '/apbdes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/infografis': typeof InfografisRouteWithChildren
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/admin/apbdes': typeof AdminApbdesRoute
  '/admin/bansos': typeof AdminBansosRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/penduduk': typeof AdminPendudukRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stunting': typeof AdminStuntingRoute
  '/berita/$id': typeof BeritaIdRoute
  '/infografis/apbdes': typeof InfografisApbdesRoute
  '/infografis/bansos': typeof InfografisBansosRoute
  '/infografis/penduduk': typeof InfografisPendudukRoute
  '/infografis/stunting': typeof InfografisStuntingRoute
  '/admin/': typeof AdminIndexRoute
  '/berita/': typeof BeritaIndexRoute
  '/infografis/': typeof InfografisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/admin/apbdes': typeof AdminApbdesRoute
  '/admin/bansos': typeof AdminBansosRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/penduduk': typeof AdminPendudukRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stunting': typeof AdminStuntingRoute
  '/berita/$id': typeof BeritaIdRoute
  '/infografis/apbdes': typeof InfografisApbdesRoute
  '/infografis/bansos': typeof InfografisBansosRoute
  '/infografis/penduduk': typeof InfografisPendudukRoute
  '/infografis/stunting': typeof InfografisStuntingRoute
  '/admin': typeof AdminIndexRoute
  '/berita': typeof BeritaIndexRoute
  '/infografis': typeof InfografisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/infografis': typeof InfografisRouteWithChildren
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/admin/apbdes': typeof AdminApbdesRoute
  '/admin/bansos': typeof AdminBansosRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/penduduk': typeof AdminPendudukRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stunting': typeof AdminStuntingRoute
  '/berita/$id': typeof BeritaIdRoute
  '/infografis/apbdes': typeof InfografisApbdesRoute
  '/infografis/bansos': typeof InfografisBansosRoute
  '/infografis/penduduk': typeof InfografisPendudukRoute
  '/infografis/stunting': typeof InfografisStuntingRoute
  '/admin/': typeof AdminIndexRoute
  '/berita/': typeof BeritaIndexRoute
  '/infografis/': typeof InfografisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/infografis'
    | '/kontak'
    | '/login'
    | '/profil'
    | '/admin/apbdes'
    | '/admin/bansos'
    | '/admin/berita'
    | '/admin/penduduk'
    | '/admin/settings'
    | '/admin/stunting'
    | '/berita/$id'
    | '/infografis/apbdes'
    | '/infografis/bansos'
    | '/infografis/penduduk'
    | '/infografis/stunting'
    | '/admin/'
    | '/berita/'
    | '/infografis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontak'
    | '/login'
    | '/profil'
    | '/admin/apbdes'
    | '/admin/bansos'
    | '/admin/berita'
    | '/admin/penduduk'
    | '/admin/settings'
    | '/admin/stunting'
    | '/berita/$id'
    | '/infografis/apbdes'
    | '/infografis/bansos'
    | '/infografis/penduduk'
    | '/infografis/stunting'
    | '/admin'
    | '/berita'
    | '/infografis'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/infografis'
    | '/kontak'
    | '/login'
    | '/profil'
    | '/admin/apbdes'
    | '/admin/bansos'
    | '/admin/berita'
    | '/admin/penduduk'
    | '/admin/settings'
    | '/admin/stunting'
    | '/berita/$id'
    | '/infografis/apbdes'
    | '/infografis/bansos'
    | '/infografis/penduduk'
    | '/infografis/stunting'
    | '/admin/'
    | '/berita/'
    | '/infografis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  InfografisRoute: typeof InfografisRouteWithChildren
  KontakRoute: typeof KontakRoute
  LoginRoute: typeof LoginRoute
  ProfilRoute: typeof ProfilRoute
  BeritaIdRoute: typeof BeritaIdRoute
  BeritaIndexRoute: typeof BeritaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infografis': {
      id: '/infografis'
      path: '/infografis'
      fullPath: '/infografis'
      preLoaderRoute: typeof InfografisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infografis/': {
      id: '/infografis/'
      path: '/'
      fullPath: '/infografis/'
      preLoaderRoute: typeof InfografisIndexRouteImport
      parentRoute: typeof InfografisRoute
    }
    '/berita/': {
      id: '/berita/'
      path: '/berita'
      fullPath: '/berita/'
      preLoaderRoute: typeof BeritaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/infografis/stunting': {
      id: '/infografis/stunting'
      path: '/stunting'
      fullPath: '/infografis/stunting'
      preLoaderRoute: typeof InfografisStuntingRouteImport
      parentRoute: typeof InfografisRoute
    }
    '/infografis/penduduk': {
      id: '/infografis/penduduk'
      path: '/penduduk'
      fullPath: '/infografis/penduduk'
      preLoaderRoute: typeof InfografisPendudukRouteImport
      parentRoute: typeof InfografisRoute
    }
    '/infografis/bansos': {
      id: '/infografis/bansos'
      path: '/bansos'
      fullPath: '/infografis/bansos'
      preLoaderRoute: typeof InfografisBansosRouteImport
      parentRoute: typeof InfografisRoute
    }
    '/infografis/apbdes': {
      id: '/infografis/apbdes'
      path: '/apbdes'
      fullPath: '/infografis/apbdes'
      preLoaderRoute: typeof InfografisApbdesRouteImport
      parentRoute: typeof InfografisRoute
    }
    '/berita/$id': {
      id: '/berita/$id'
      path: '/berita/$id'
      fullPath: '/berita/$id'
      preLoaderRoute: typeof BeritaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stunting': {
      id: '/admin/stunting'
      path: '/stunting'
      fullPath: '/admin/stunting'
      preLoaderRoute: typeof AdminStuntingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/penduduk': {
      id: '/admin/penduduk'
      path: '/penduduk'
      fullPath: '/admin/penduduk'
      preLoaderRoute: typeof AdminPendudukRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/berita': {
      id: '/admin/berita'
      path: '/berita'
      fullPath: '/admin/berita'
      preLoaderRoute: typeof AdminBeritaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bansos': {
      id: '/admin/bansos'
      path: '/bansos'
      fullPath: '/admin/bansos'
      preLoaderRoute: typeof AdminBansosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/apbdes': {
      id: '/admin/apbdes'
      path: '/apbdes'
      fullPath: '/admin/apbdes'
      preLoaderRoute: typeof AdminApbdesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApbdesRoute: typeof AdminApbdesRoute
  AdminBansosRoute: typeof AdminBansosRoute
  AdminBeritaRoute: typeof AdminBeritaRoute
  AdminPendudukRoute: typeof AdminPendudukRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStuntingRoute: typeof AdminStuntingRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApbdesRoute: AdminApbdesRoute,
  AdminBansosRoute: AdminBansosRoute,
  AdminBeritaRoute: AdminBeritaRoute,
  AdminPendudukRoute: AdminPendudukRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStuntingRoute: AdminStuntingRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InfografisRouteChildren {
  InfografisApbdesRoute: typeof InfografisApbdesRoute
  InfografisBansosRoute: typeof InfografisBansosRoute
  InfografisPendudukRoute: typeof InfografisPendudukRoute
  InfografisStuntingRoute: typeof InfografisStuntingRoute
  InfografisIndexRoute: typeof InfografisIndexRoute
}

const InfografisRouteChildren: InfografisRouteChildren = {
  InfografisApbdesRoute: InfografisApbdesRoute,
  InfografisBansosRoute: InfografisBansosRoute,
  InfografisPendudukRoute: InfografisPendudukRoute,
  InfografisStuntingRoute: InfografisStuntingRoute,
  InfografisIndexRoute: InfografisIndexRoute,
}

const InfografisRouteWithChildren = InfografisRoute._addFileChildren(
  InfografisRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  InfografisRoute: InfografisRouteWithChildren,
  KontakRoute: KontakRoute,
  LoginRoute: LoginRoute,
  ProfilRoute: ProfilRoute,
  BeritaIdRoute: BeritaIdRoute,
  BeritaIndexRoute: BeritaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
