/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as InfografisRouteImport } from './routes/infografis'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InfografisIndexRouteImport } from './routes/infografis/index'
import { Route as BeritaIndexRouteImport } from './routes/berita/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as InfografisStuntingRouteImport } from './routes/infografis/stunting'
import { Route as InfografisPendudukRouteImport } from './routes/infografis/penduduk'
import { Route as InfografisBansosRouteImport } from './routes/infografis/bansos'
import { Route as InfografisApbdesRouteImport } from './routes/infografis/apbdes'
import { Route as BeritaSlugRouteImport } from './routes/berita/$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPengaduanRouteImport } from './routes/admin/pengaduan'
import { Route as AdminBeritaIndexRouteImport } from './routes/admin/berita.index'
import { Route as AdminMasterUsersRouteImport } from './routes/admin/master/users'
import { Route as AdminMasterKategoriPengaduanRouteImport } from './routes/admin/master/kategori-pengaduan'
import { Route as AdminMasterKategoriRouteImport } from './routes/admin/master/kategori'
import { Route as AdminKontenRtRwRouteImport } from './routes/admin/konten/rt-rw'
import { Route as AdminKontenProfilRouteImport } from './routes/admin/konten/profil'
import { Route as AdminKontenPerangkatRouteImport } from './routes/admin/konten/perangkat'
import { Route as AdminKontenKontakRouteImport } from './routes/admin/konten/kontak'
import { Route as AdminKontenBerandaRouteImport } from './routes/admin/konten/beranda'
import { Route as AdminInfografisStuntingRouteImport } from './routes/admin/infografis/stunting'
import { Route as AdminInfografisPendudukRouteImport } from './routes/admin/infografis/penduduk'
import { Route as AdminInfografisBansosRouteImport } from './routes/admin/infografis/bansos'
import { Route as AdminInfografisApbdesRouteImport } from './routes/admin/infografis/apbdes'
import { Route as AdminBeritaTambahRouteImport } from './routes/admin/berita.tambah'
import { Route as AdminAnalyticTurnstileRouteImport } from './routes/admin/analytic/turnstile'
import { Route as AdminAnalyticR2RouteImport } from './routes/admin/analytic/r2'
import { Route as AdminKontenKelembagaanIndexRouteImport } from './routes/admin/konten/kelembagaan.index'
import { Route as AdminKontenKelembagaanTambahRouteImport } from './routes/admin/konten/kelembagaan.tambah'
import { Route as AdminInfografisApbdesTahunIdRouteImport } from './routes/admin/infografis/apbdes_.$tahunId'
import { Route as AdminBeritaEditIdRouteImport } from './routes/admin/berita.edit.$id'
import { Route as AdminKontenKelembagaanKelolaIdRouteImport } from './routes/admin/konten/kelembagaan.kelola.$id'

const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const InfografisRoute = InfografisRouteImport.update({
  id: '/infografis',
  path: '/infografis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfografisIndexRoute = InfografisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InfografisRoute,
} as any)
const BeritaIndexRoute = BeritaIndexRouteImport.update({
  id: '/berita/',
  path: '/berita/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const InfografisStuntingRoute = InfografisStuntingRouteImport.update({
  id: '/stunting',
  path: '/stunting',
  getParentRoute: () => InfografisRoute,
} as any)
const InfografisPendudukRoute = InfografisPendudukRouteImport.update({
  id: '/penduduk',
  path: '/penduduk',
  getParentRoute: () => InfografisRoute,
} as any)
const InfografisBansosRoute = InfografisBansosRouteImport.update({
  id: '/bansos',
  path: '/bansos',
  getParentRoute: () => InfografisRoute,
} as any)
const InfografisApbdesRoute = InfografisApbdesRouteImport.update({
  id: '/apbdes',
  path: '/apbdes',
  getParentRoute: () => InfografisRoute,
} as any)
const BeritaSlugRoute = BeritaSlugRouteImport.update({
  id: '/berita/$slug',
  path: '/berita/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPengaduanRoute = AdminPengaduanRouteImport.update({
  id: '/pengaduan',
  path: '/pengaduan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBeritaIndexRoute = AdminBeritaIndexRouteImport.update({
  id: '/berita/',
  path: '/berita/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMasterUsersRoute = AdminMasterUsersRouteImport.update({
  id: '/master/users',
  path: '/master/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMasterKategoriPengaduanRoute =
  AdminMasterKategoriPengaduanRouteImport.update({
    id: '/master/kategori-pengaduan',
    path: '/master/kategori-pengaduan',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMasterKategoriRoute = AdminMasterKategoriRouteImport.update({
  id: '/master/kategori',
  path: '/master/kategori',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKontenRtRwRoute = AdminKontenRtRwRouteImport.update({
  id: '/konten/rt-rw',
  path: '/konten/rt-rw',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKontenProfilRoute = AdminKontenProfilRouteImport.update({
  id: '/konten/profil',
  path: '/konten/profil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKontenPerangkatRoute = AdminKontenPerangkatRouteImport.update({
  id: '/konten/perangkat',
  path: '/konten/perangkat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKontenKontakRoute = AdminKontenKontakRouteImport.update({
  id: '/konten/kontak',
  path: '/konten/kontak',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKontenBerandaRoute = AdminKontenBerandaRouteImport.update({
  id: '/konten/beranda',
  path: '/konten/beranda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfografisStuntingRoute = AdminInfografisStuntingRouteImport.update({
  id: '/infografis/stunting',
  path: '/infografis/stunting',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfografisPendudukRoute = AdminInfografisPendudukRouteImport.update({
  id: '/infografis/penduduk',
  path: '/infografis/penduduk',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfografisBansosRoute = AdminInfografisBansosRouteImport.update({
  id: '/infografis/bansos',
  path: '/infografis/bansos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfografisApbdesRoute = AdminInfografisApbdesRouteImport.update({
  id: '/infografis/apbdes',
  path: '/infografis/apbdes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBeritaTambahRoute = AdminBeritaTambahRouteImport.update({
  id: '/berita/tambah',
  path: '/berita/tambah',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticTurnstileRoute = AdminAnalyticTurnstileRouteImport.update({
  id: '/analytic/turnstile',
  path: '/analytic/turnstile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticR2Route = AdminAnalyticR2RouteImport.update({
  id: '/analytic/r2',
  path: '/analytic/r2',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKontenKelembagaanIndexRoute =
  AdminKontenKelembagaanIndexRouteImport.update({
    id: '/konten/kelembagaan/',
    path: '/konten/kelembagaan/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminKontenKelembagaanTambahRoute =
  AdminKontenKelembagaanTambahRouteImport.update({
    id: '/konten/kelembagaan/tambah',
    path: '/konten/kelembagaan/tambah',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInfografisApbdesTahunIdRoute =
  AdminInfografisApbdesTahunIdRouteImport.update({
    id: '/infografis/apbdes_/$tahunId',
    path: '/infografis/apbdes/$tahunId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBeritaEditIdRoute = AdminBeritaEditIdRouteImport.update({
  id: '/berita/edit/$id',
  path: '/berita/edit/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKontenKelembagaanKelolaIdRoute =
  AdminKontenKelembagaanKelolaIdRouteImport.update({
    id: '/konten/kelembagaan/kelola/$id',
    path: '/konten/kelembagaan/kelola/$id',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/infografis': typeof InfografisRouteWithChildren
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/admin/pengaduan': typeof AdminPengaduanRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/infografis/apbdes': typeof InfografisApbdesRoute
  '/infografis/bansos': typeof InfografisBansosRoute
  '/infografis/penduduk': typeof InfografisPendudukRoute
  '/infografis/stunting': typeof InfografisStuntingRoute
  '/admin/': typeof AdminIndexRoute
  '/berita/': typeof BeritaIndexRoute
  '/infografis/': typeof InfografisIndexRoute
  '/admin/analytic/r2': typeof AdminAnalyticR2Route
  '/admin/analytic/turnstile': typeof AdminAnalyticTurnstileRoute
  '/admin/berita/tambah': typeof AdminBeritaTambahRoute
  '/admin/infografis/apbdes': typeof AdminInfografisApbdesRoute
  '/admin/infografis/bansos': typeof AdminInfografisBansosRoute
  '/admin/infografis/penduduk': typeof AdminInfografisPendudukRoute
  '/admin/infografis/stunting': typeof AdminInfografisStuntingRoute
  '/admin/konten/beranda': typeof AdminKontenBerandaRoute
  '/admin/konten/kontak': typeof AdminKontenKontakRoute
  '/admin/konten/perangkat': typeof AdminKontenPerangkatRoute
  '/admin/konten/profil': typeof AdminKontenProfilRoute
  '/admin/konten/rt-rw': typeof AdminKontenRtRwRoute
  '/admin/master/kategori': typeof AdminMasterKategoriRoute
  '/admin/master/kategori-pengaduan': typeof AdminMasterKategoriPengaduanRoute
  '/admin/master/users': typeof AdminMasterUsersRoute
  '/admin/berita/': typeof AdminBeritaIndexRoute
  '/admin/berita/edit/$id': typeof AdminBeritaEditIdRoute
  '/admin/infografis/apbdes/$tahunId': typeof AdminInfografisApbdesTahunIdRoute
  '/admin/konten/kelembagaan/tambah': typeof AdminKontenKelembagaanTambahRoute
  '/admin/konten/kelembagaan/': typeof AdminKontenKelembagaanIndexRoute
  '/admin/konten/kelembagaan/kelola/$id': typeof AdminKontenKelembagaanKelolaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/admin/pengaduan': typeof AdminPengaduanRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/infografis/apbdes': typeof InfografisApbdesRoute
  '/infografis/bansos': typeof InfografisBansosRoute
  '/infografis/penduduk': typeof InfografisPendudukRoute
  '/infografis/stunting': typeof InfografisStuntingRoute
  '/admin': typeof AdminIndexRoute
  '/berita': typeof BeritaIndexRoute
  '/infografis': typeof InfografisIndexRoute
  '/admin/analytic/r2': typeof AdminAnalyticR2Route
  '/admin/analytic/turnstile': typeof AdminAnalyticTurnstileRoute
  '/admin/berita/tambah': typeof AdminBeritaTambahRoute
  '/admin/infografis/apbdes': typeof AdminInfografisApbdesRoute
  '/admin/infografis/bansos': typeof AdminInfografisBansosRoute
  '/admin/infografis/penduduk': typeof AdminInfografisPendudukRoute
  '/admin/infografis/stunting': typeof AdminInfografisStuntingRoute
  '/admin/konten/beranda': typeof AdminKontenBerandaRoute
  '/admin/konten/kontak': typeof AdminKontenKontakRoute
  '/admin/konten/perangkat': typeof AdminKontenPerangkatRoute
  '/admin/konten/profil': typeof AdminKontenProfilRoute
  '/admin/konten/rt-rw': typeof AdminKontenRtRwRoute
  '/admin/master/kategori': typeof AdminMasterKategoriRoute
  '/admin/master/kategori-pengaduan': typeof AdminMasterKategoriPengaduanRoute
  '/admin/master/users': typeof AdminMasterUsersRoute
  '/admin/berita': typeof AdminBeritaIndexRoute
  '/admin/berita/edit/$id': typeof AdminBeritaEditIdRoute
  '/admin/infografis/apbdes/$tahunId': typeof AdminInfografisApbdesTahunIdRoute
  '/admin/konten/kelembagaan/tambah': typeof AdminKontenKelembagaanTambahRoute
  '/admin/konten/kelembagaan': typeof AdminKontenKelembagaanIndexRoute
  '/admin/konten/kelembagaan/kelola/$id': typeof AdminKontenKelembagaanKelolaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/infografis': typeof InfografisRouteWithChildren
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/admin/pengaduan': typeof AdminPengaduanRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/infografis/apbdes': typeof InfografisApbdesRoute
  '/infografis/bansos': typeof InfografisBansosRoute
  '/infografis/penduduk': typeof InfografisPendudukRoute
  '/infografis/stunting': typeof InfografisStuntingRoute
  '/admin/': typeof AdminIndexRoute
  '/berita/': typeof BeritaIndexRoute
  '/infografis/': typeof InfografisIndexRoute
  '/admin/analytic/r2': typeof AdminAnalyticR2Route
  '/admin/analytic/turnstile': typeof AdminAnalyticTurnstileRoute
  '/admin/berita/tambah': typeof AdminBeritaTambahRoute
  '/admin/infografis/apbdes': typeof AdminInfografisApbdesRoute
  '/admin/infografis/bansos': typeof AdminInfografisBansosRoute
  '/admin/infografis/penduduk': typeof AdminInfografisPendudukRoute
  '/admin/infografis/stunting': typeof AdminInfografisStuntingRoute
  '/admin/konten/beranda': typeof AdminKontenBerandaRoute
  '/admin/konten/kontak': typeof AdminKontenKontakRoute
  '/admin/konten/perangkat': typeof AdminKontenPerangkatRoute
  '/admin/konten/profil': typeof AdminKontenProfilRoute
  '/admin/konten/rt-rw': typeof AdminKontenRtRwRoute
  '/admin/master/kategori': typeof AdminMasterKategoriRoute
  '/admin/master/kategori-pengaduan': typeof AdminMasterKategoriPengaduanRoute
  '/admin/master/users': typeof AdminMasterUsersRoute
  '/admin/berita/': typeof AdminBeritaIndexRoute
  '/admin/berita/edit/$id': typeof AdminBeritaEditIdRoute
  '/admin/infografis/apbdes_/$tahunId': typeof AdminInfografisApbdesTahunIdRoute
  '/admin/konten/kelembagaan/tambah': typeof AdminKontenKelembagaanTambahRoute
  '/admin/konten/kelembagaan/': typeof AdminKontenKelembagaanIndexRoute
  '/admin/konten/kelembagaan/kelola/$id': typeof AdminKontenKelembagaanKelolaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/infografis'
    | '/kontak'
    | '/login'
    | '/profil'
    | '/admin/pengaduan'
    | '/admin/settings'
    | '/berita/$slug'
    | '/infografis/apbdes'
    | '/infografis/bansos'
    | '/infografis/penduduk'
    | '/infografis/stunting'
    | '/admin/'
    | '/berita/'
    | '/infografis/'
    | '/admin/analytic/r2'
    | '/admin/analytic/turnstile'
    | '/admin/berita/tambah'
    | '/admin/infografis/apbdes'
    | '/admin/infografis/bansos'
    | '/admin/infografis/penduduk'
    | '/admin/infografis/stunting'
    | '/admin/konten/beranda'
    | '/admin/konten/kontak'
    | '/admin/konten/perangkat'
    | '/admin/konten/profil'
    | '/admin/konten/rt-rw'
    | '/admin/master/kategori'
    | '/admin/master/kategori-pengaduan'
    | '/admin/master/users'
    | '/admin/berita/'
    | '/admin/berita/edit/$id'
    | '/admin/infografis/apbdes/$tahunId'
    | '/admin/konten/kelembagaan/tambah'
    | '/admin/konten/kelembagaan/'
    | '/admin/konten/kelembagaan/kelola/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontak'
    | '/login'
    | '/profil'
    | '/admin/pengaduan'
    | '/admin/settings'
    | '/berita/$slug'
    | '/infografis/apbdes'
    | '/infografis/bansos'
    | '/infografis/penduduk'
    | '/infografis/stunting'
    | '/admin'
    | '/berita'
    | '/infografis'
    | '/admin/analytic/r2'
    | '/admin/analytic/turnstile'
    | '/admin/berita/tambah'
    | '/admin/infografis/apbdes'
    | '/admin/infografis/bansos'
    | '/admin/infografis/penduduk'
    | '/admin/infografis/stunting'
    | '/admin/konten/beranda'
    | '/admin/konten/kontak'
    | '/admin/konten/perangkat'
    | '/admin/konten/profil'
    | '/admin/konten/rt-rw'
    | '/admin/master/kategori'
    | '/admin/master/kategori-pengaduan'
    | '/admin/master/users'
    | '/admin/berita'
    | '/admin/berita/edit/$id'
    | '/admin/infografis/apbdes/$tahunId'
    | '/admin/konten/kelembagaan/tambah'
    | '/admin/konten/kelembagaan'
    | '/admin/konten/kelembagaan/kelola/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/infografis'
    | '/kontak'
    | '/login'
    | '/profil'
    | '/admin/pengaduan'
    | '/admin/settings'
    | '/berita/$slug'
    | '/infografis/apbdes'
    | '/infografis/bansos'
    | '/infografis/penduduk'
    | '/infografis/stunting'
    | '/admin/'
    | '/berita/'
    | '/infografis/'
    | '/admin/analytic/r2'
    | '/admin/analytic/turnstile'
    | '/admin/berita/tambah'
    | '/admin/infografis/apbdes'
    | '/admin/infografis/bansos'
    | '/admin/infografis/penduduk'
    | '/admin/infografis/stunting'
    | '/admin/konten/beranda'
    | '/admin/konten/kontak'
    | '/admin/konten/perangkat'
    | '/admin/konten/profil'
    | '/admin/konten/rt-rw'
    | '/admin/master/kategori'
    | '/admin/master/kategori-pengaduan'
    | '/admin/master/users'
    | '/admin/berita/'
    | '/admin/berita/edit/$id'
    | '/admin/infografis/apbdes_/$tahunId'
    | '/admin/konten/kelembagaan/tambah'
    | '/admin/konten/kelembagaan/'
    | '/admin/konten/kelembagaan/kelola/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  InfografisRoute: typeof InfografisRouteWithChildren
  KontakRoute: typeof KontakRoute
  LoginRoute: typeof LoginRoute
  ProfilRoute: typeof ProfilRoute
  BeritaSlugRoute: typeof BeritaSlugRoute
  BeritaIndexRoute: typeof BeritaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infografis': {
      id: '/infografis'
      path: '/infografis'
      fullPath: '/infografis'
      preLoaderRoute: typeof InfografisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infografis/': {
      id: '/infografis/'
      path: '/'
      fullPath: '/infografis/'
      preLoaderRoute: typeof InfografisIndexRouteImport
      parentRoute: typeof InfografisRoute
    }
    '/berita/': {
      id: '/berita/'
      path: '/berita'
      fullPath: '/berita/'
      preLoaderRoute: typeof BeritaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/infografis/stunting': {
      id: '/infografis/stunting'
      path: '/stunting'
      fullPath: '/infografis/stunting'
      preLoaderRoute: typeof InfografisStuntingRouteImport
      parentRoute: typeof InfografisRoute
    }
    '/infografis/penduduk': {
      id: '/infografis/penduduk'
      path: '/penduduk'
      fullPath: '/infografis/penduduk'
      preLoaderRoute: typeof InfografisPendudukRouteImport
      parentRoute: typeof InfografisRoute
    }
    '/infografis/bansos': {
      id: '/infografis/bansos'
      path: '/bansos'
      fullPath: '/infografis/bansos'
      preLoaderRoute: typeof InfografisBansosRouteImport
      parentRoute: typeof InfografisRoute
    }
    '/infografis/apbdes': {
      id: '/infografis/apbdes'
      path: '/apbdes'
      fullPath: '/infografis/apbdes'
      preLoaderRoute: typeof InfografisApbdesRouteImport
      parentRoute: typeof InfografisRoute
    }
    '/berita/$slug': {
      id: '/berita/$slug'
      path: '/berita/$slug'
      fullPath: '/berita/$slug'
      preLoaderRoute: typeof BeritaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengaduan': {
      id: '/admin/pengaduan'
      path: '/pengaduan'
      fullPath: '/admin/pengaduan'
      preLoaderRoute: typeof AdminPengaduanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/berita/': {
      id: '/admin/berita/'
      path: '/berita'
      fullPath: '/admin/berita/'
      preLoaderRoute: typeof AdminBeritaIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/master/users': {
      id: '/admin/master/users'
      path: '/master/users'
      fullPath: '/admin/master/users'
      preLoaderRoute: typeof AdminMasterUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/master/kategori-pengaduan': {
      id: '/admin/master/kategori-pengaduan'
      path: '/master/kategori-pengaduan'
      fullPath: '/admin/master/kategori-pengaduan'
      preLoaderRoute: typeof AdminMasterKategoriPengaduanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/master/kategori': {
      id: '/admin/master/kategori'
      path: '/master/kategori'
      fullPath: '/admin/master/kategori'
      preLoaderRoute: typeof AdminMasterKategoriRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/konten/rt-rw': {
      id: '/admin/konten/rt-rw'
      path: '/konten/rt-rw'
      fullPath: '/admin/konten/rt-rw'
      preLoaderRoute: typeof AdminKontenRtRwRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/konten/profil': {
      id: '/admin/konten/profil'
      path: '/konten/profil'
      fullPath: '/admin/konten/profil'
      preLoaderRoute: typeof AdminKontenProfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/konten/perangkat': {
      id: '/admin/konten/perangkat'
      path: '/konten/perangkat'
      fullPath: '/admin/konten/perangkat'
      preLoaderRoute: typeof AdminKontenPerangkatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/konten/kontak': {
      id: '/admin/konten/kontak'
      path: '/konten/kontak'
      fullPath: '/admin/konten/kontak'
      preLoaderRoute: typeof AdminKontenKontakRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/konten/beranda': {
      id: '/admin/konten/beranda'
      path: '/konten/beranda'
      fullPath: '/admin/konten/beranda'
      preLoaderRoute: typeof AdminKontenBerandaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/infografis/stunting': {
      id: '/admin/infografis/stunting'
      path: '/infografis/stunting'
      fullPath: '/admin/infografis/stunting'
      preLoaderRoute: typeof AdminInfografisStuntingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/infografis/penduduk': {
      id: '/admin/infografis/penduduk'
      path: '/infografis/penduduk'
      fullPath: '/admin/infografis/penduduk'
      preLoaderRoute: typeof AdminInfografisPendudukRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/infografis/bansos': {
      id: '/admin/infografis/bansos'
      path: '/infografis/bansos'
      fullPath: '/admin/infografis/bansos'
      preLoaderRoute: typeof AdminInfografisBansosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/infografis/apbdes': {
      id: '/admin/infografis/apbdes'
      path: '/infografis/apbdes'
      fullPath: '/admin/infografis/apbdes'
      preLoaderRoute: typeof AdminInfografisApbdesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/berita/tambah': {
      id: '/admin/berita/tambah'
      path: '/berita/tambah'
      fullPath: '/admin/berita/tambah'
      preLoaderRoute: typeof AdminBeritaTambahRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytic/turnstile': {
      id: '/admin/analytic/turnstile'
      path: '/analytic/turnstile'
      fullPath: '/admin/analytic/turnstile'
      preLoaderRoute: typeof AdminAnalyticTurnstileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytic/r2': {
      id: '/admin/analytic/r2'
      path: '/analytic/r2'
      fullPath: '/admin/analytic/r2'
      preLoaderRoute: typeof AdminAnalyticR2RouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/konten/kelembagaan/': {
      id: '/admin/konten/kelembagaan/'
      path: '/konten/kelembagaan'
      fullPath: '/admin/konten/kelembagaan/'
      preLoaderRoute: typeof AdminKontenKelembagaanIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/konten/kelembagaan/tambah': {
      id: '/admin/konten/kelembagaan/tambah'
      path: '/konten/kelembagaan/tambah'
      fullPath: '/admin/konten/kelembagaan/tambah'
      preLoaderRoute: typeof AdminKontenKelembagaanTambahRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/infografis/apbdes_/$tahunId': {
      id: '/admin/infografis/apbdes_/$tahunId'
      path: '/infografis/apbdes/$tahunId'
      fullPath: '/admin/infografis/apbdes/$tahunId'
      preLoaderRoute: typeof AdminInfografisApbdesTahunIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/berita/edit/$id': {
      id: '/admin/berita/edit/$id'
      path: '/berita/edit/$id'
      fullPath: '/admin/berita/edit/$id'
      preLoaderRoute: typeof AdminBeritaEditIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/konten/kelembagaan/kelola/$id': {
      id: '/admin/konten/kelembagaan/kelola/$id'
      path: '/konten/kelembagaan/kelola/$id'
      fullPath: '/admin/konten/kelembagaan/kelola/$id'
      preLoaderRoute: typeof AdminKontenKelembagaanKelolaIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPengaduanRoute: typeof AdminPengaduanRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnalyticR2Route: typeof AdminAnalyticR2Route
  AdminAnalyticTurnstileRoute: typeof AdminAnalyticTurnstileRoute
  AdminBeritaTambahRoute: typeof AdminBeritaTambahRoute
  AdminInfografisApbdesRoute: typeof AdminInfografisApbdesRoute
  AdminInfografisBansosRoute: typeof AdminInfografisBansosRoute
  AdminInfografisPendudukRoute: typeof AdminInfografisPendudukRoute
  AdminInfografisStuntingRoute: typeof AdminInfografisStuntingRoute
  AdminKontenBerandaRoute: typeof AdminKontenBerandaRoute
  AdminKontenKontakRoute: typeof AdminKontenKontakRoute
  AdminKontenPerangkatRoute: typeof AdminKontenPerangkatRoute
  AdminKontenProfilRoute: typeof AdminKontenProfilRoute
  AdminKontenRtRwRoute: typeof AdminKontenRtRwRoute
  AdminMasterKategoriRoute: typeof AdminMasterKategoriRoute
  AdminMasterKategoriPengaduanRoute: typeof AdminMasterKategoriPengaduanRoute
  AdminMasterUsersRoute: typeof AdminMasterUsersRoute
  AdminBeritaIndexRoute: typeof AdminBeritaIndexRoute
  AdminBeritaEditIdRoute: typeof AdminBeritaEditIdRoute
  AdminInfografisApbdesTahunIdRoute: typeof AdminInfografisApbdesTahunIdRoute
  AdminKontenKelembagaanTambahRoute: typeof AdminKontenKelembagaanTambahRoute
  AdminKontenKelembagaanIndexRoute: typeof AdminKontenKelembagaanIndexRoute
  AdminKontenKelembagaanKelolaIdRoute: typeof AdminKontenKelembagaanKelolaIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPengaduanRoute: AdminPengaduanRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAnalyticR2Route: AdminAnalyticR2Route,
  AdminAnalyticTurnstileRoute: AdminAnalyticTurnstileRoute,
  AdminBeritaTambahRoute: AdminBeritaTambahRoute,
  AdminInfografisApbdesRoute: AdminInfografisApbdesRoute,
  AdminInfografisBansosRoute: AdminInfografisBansosRoute,
  AdminInfografisPendudukRoute: AdminInfografisPendudukRoute,
  AdminInfografisStuntingRoute: AdminInfografisStuntingRoute,
  AdminKontenBerandaRoute: AdminKontenBerandaRoute,
  AdminKontenKontakRoute: AdminKontenKontakRoute,
  AdminKontenPerangkatRoute: AdminKontenPerangkatRoute,
  AdminKontenProfilRoute: AdminKontenProfilRoute,
  AdminKontenRtRwRoute: AdminKontenRtRwRoute,
  AdminMasterKategoriRoute: AdminMasterKategoriRoute,
  AdminMasterKategoriPengaduanRoute: AdminMasterKategoriPengaduanRoute,
  AdminMasterUsersRoute: AdminMasterUsersRoute,
  AdminBeritaIndexRoute: AdminBeritaIndexRoute,
  AdminBeritaEditIdRoute: AdminBeritaEditIdRoute,
  AdminInfografisApbdesTahunIdRoute: AdminInfografisApbdesTahunIdRoute,
  AdminKontenKelembagaanTambahRoute: AdminKontenKelembagaanTambahRoute,
  AdminKontenKelembagaanIndexRoute: AdminKontenKelembagaanIndexRoute,
  AdminKontenKelembagaanKelolaIdRoute: AdminKontenKelembagaanKelolaIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InfografisRouteChildren {
  InfografisApbdesRoute: typeof InfografisApbdesRoute
  InfografisBansosRoute: typeof InfografisBansosRoute
  InfografisPendudukRoute: typeof InfografisPendudukRoute
  InfografisStuntingRoute: typeof InfografisStuntingRoute
  InfografisIndexRoute: typeof InfografisIndexRoute
}

const InfografisRouteChildren: InfografisRouteChildren = {
  InfografisApbdesRoute: InfografisApbdesRoute,
  InfografisBansosRoute: InfografisBansosRoute,
  InfografisPendudukRoute: InfografisPendudukRoute,
  InfografisStuntingRoute: InfografisStuntingRoute,
  InfografisIndexRoute: InfografisIndexRoute,
}

const InfografisRouteWithChildren = InfografisRoute._addFileChildren(
  InfografisRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  InfografisRoute: InfografisRouteWithChildren,
  KontakRoute: KontakRoute,
  LoginRoute: LoginRoute,
  ProfilRoute: ProfilRoute,
  BeritaSlugRoute: BeritaSlugRoute,
  BeritaIndexRoute: BeritaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
